# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Download Advent of Code Input Data and Create Source / Test Files from Template

on:
  schedule:
    - cron: "0 5 1-25 12 *"
  workflow_dispatch:

permissions:
  contents: write

env:
  AOC_DAY: $(date +"%-d")
  AOC_YEAR: $(date +%Y)
  AOC_COOKIE: "session=${{ secrets.AOC_COOKIE_SESSION }}"
  AOC_AGENT: "User-Agent: ${{ secrets.AOC_USER_AGENT }}"
  AOC_FILE: "src/main/resources/year$(date +%Y)/input/Day$(date +%-d).input"
  AOC_URL: "https://adventofcode.com/$(date +%Y)/day/$(date +%-d)/input"

jobs:
  download-days-input-and-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto

      - name: Make directories if not exists
        run: |
          mkdir -p src/main/resources/year${{ env.AOC_YEAR }}/input
          mkdir -p "src/main/scala/org/advent/year${{ env.AOC_YEAR }}"
          mkdir -p "src/test/scala/org/advent/year${{ env.AOC_YEAR }}"

      - name: Download Input Data
        run: |
          curl --cookie "${{ env.AOC_COOKIE }}" -H "${{ env.AOC_AGENT }}" -o "${{ env.AOC_FILE }}" "${{ env.AOC_URL }}"

      - name: Create new source and test files from templates
        run: |
          cp -u "src/main/scala/org/advent/templates/SolutionTemplate.tpl" "src/main/scala/org/advent/year${{ env.AOC_YEAR }}/Day${{ env.AOC_DAY }}.scala"
          cp -u "src/test/scala/org/advent/templates/SolutionTemplateTest.tpl" "src/test/scala/org/advent/year${{ env.AOC_YEAR }}/Day${{ env.AOC_DAY }}Test.scala"

      - name: Update source and test files to use current day variables
        run: |
          sed -i "s/{{ aoc_year }}/${{ env.AOC_YEAR }}/g" "src/main/scala/org/advent/year${{ env.AOC_YEAR }}/Day${{ env.AOC_DAY }}.scala"
          sed -i "s/{{ aoc_day }}/${{ env.AOC_DAY }}/g" "src/main/scala/org/advent/year${{ env.AOC_YEAR }}/Day${{ env.AOC_DAY }}.scala"
          sed -i "s/{{ aoc_year }}/${{ env.AOC_YEAR }}/g" "src/test/scala/org/advent/year${{ env.AOC_YEAR }}/Day${{ env.AOC_DAY }}Test.scala"
          sed -i "s/{{ aoc_day }}/${{ env.AOC_DAY }}/g" "src/test/scala/org/advent/year${{ env.AOC_YEAR }}/Day${{ env.AOC_DAY }}Test.scala"      

      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Daily input file update"
          add: .