# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Download Advent of Code Input Data

on:
  # Uncomment me in your repo
  # schedule:
  #   - cron: "0 5 1-25 12 *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  download-and-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto
      - name: Set AoC Date
        run: |
          echo "AOC_DAY=$(date +"%-d")" >> ${GITHUB_ENV}
          echo "AOC_YEAR=$(date +%Y)" >> ${GITHUB_ENV}
      - name: Download File
        run: |
          mkdir -p src/main/resources/year$AOC_YEAR/input
          curl --cookie "session=${{ secrets.AOC_COOKIE_SESSION }}" -H "User-Agent: ${{ secrets.AOC_USER_AGENT }}" -o "src/main/resources/year$AOC_YEAR/input/Day$AOC_DAY.input" "https://adventofcode.com/$AOC_YEAR/day/$AOC_DAY/input"
      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Daily input file update"
          add: .
